import argparse
import os
from pathlib import Path

import datasets
import pandas as pd
from datasets import DatasetDict, concatenate_datasets, load_dataset


def merge_parquet_datasets(parquet_paths, output_dir, merge_strategy="concatenate"):
    """
    Merge multiple parquet datasets generated by hatefulmemes.py
    
    Args:
        parquet_paths: List of paths to parquet files or directories containing train.parquet/test.parquet
        output_dir: Output directory to save merged datasets
        merge_strategy: How to merge datasets ("concatenate" or "separate")
    """
    
    train_datasets = []
    test_datasets = []
    
    print(f"Processing {len(parquet_paths)} dataset path(s)...")
    
    for path in parquet_paths:
        path = Path(path)
        
        if path.is_file() and path.suffix == '.parquet':
            # Single parquet file
            dataset = load_dataset("parquet", data_files=str(path))["train"]
            print(f"Loaded dataset from {path} with {len(dataset)} entries")
            
            # Determine if it's train or test based on filename
            if "train" in path.stem:
                train_datasets.append(dataset)
            elif "test" in path.stem:
                test_datasets.append(dataset)
            else:
                # Default to train if unclear
                train_datasets.append(dataset)
                
        elif path.is_dir():
            # Directory containing train.parquet and/or test.parquet
            train_path = path / "train.parquet"
            test_path = path / "test.parquet"
            
            if train_path.exists():
                train_dataset = load_dataset("parquet", data_files=str(train_path))["train"]
                train_datasets.append(train_dataset)
                print(f"Loaded train dataset from {train_path} with {len(train_dataset)} entries")
            
            if test_path.exists():
                test_dataset = load_dataset("parquet", data_files=str(test_path))["train"]
                test_datasets.append(test_dataset)
                print(f"Loaded test dataset from {test_path} with {len(test_dataset)} entries")
        else:
            print(f"Warning: {path} is not a valid parquet file or directory, skipping...")
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Merge datasets
    merged_datasets = {}
    
    if train_datasets:
        if merge_strategy == "concatenate":
            merged_train = concatenate_datasets(train_datasets)
            print(f"Merged {len(train_datasets)} train datasets into one with {len(merged_train)} total entries")
        else:
            merged_train = train_datasets
            
        merged_datasets["train"] = merged_train
        
        # Save merged train dataset
        train_output_path = os.path.join(output_dir, "train.parquet")
        merged_train.to_parquet(train_output_path)
        print(f"Saved merged train dataset to {train_output_path}")
    
    if test_datasets:
        if merge_strategy == "concatenate":
            merged_test = concatenate_datasets(test_datasets)
            print(f"Merged {len(test_datasets)} test datasets into one with {len(merged_test)} total entries")
        else:
            merged_test = test_datasets
            
        merged_datasets["test"] = merged_test
        
        # Save merged test dataset
        test_output_path = os.path.join(output_dir, "test.parquet")
        merged_test.to_parquet(test_output_path)
        print(f"Saved merged test dataset to {test_output_path}")
    
    return merged_datasets


def print_dataset_info(datasets_dict):
    """Print information about the merged datasets"""
    print("\n" + "="*50)
    print("MERGED DATASET INFORMATION")
    print("="*50)
    
    for split, dataset in datasets_dict.items():
        print(f"\n{split.upper()} DATASET:")
        print(f"  Total entries: {len(dataset)}")
        
        # Print data source distribution
        if "data_source" in dataset.column_names:
            data_sources = dataset["data_source"]
            source_counts = pd.Series(data_sources).value_counts()
            print("  Data source distribution:")
            for source, count in source_counts.items():
                print(f"    {source}: {count}")
        
        # Print column names
        print(f"  Columns: {dataset.column_names}")
        
        # Sample entry
        if len(dataset) > 0:
            print("  Sample entry keys:", list(dataset[0].keys()))


def main():
    parser = argparse.ArgumentParser(description="Merge parquet datasets generated by hatefulmemes.py")
    parser.add_argument(
        "parquet_paths", 
        nargs="+", 
        help="Paths to parquet files or directories containing train.parquet/test.parquet"
    )
    parser.add_argument(
        "--output_dir", 
        "-o", 
        required=True,
        help="Output directory to save merged datasets"
    )
    parser.add_argument(
        "--merge_strategy",
        choices=["concatenate", "separate"],
        default="concatenate",
        help="How to merge datasets: 'concatenate' (default) or 'separate'"
    )
    parser.add_argument(
        "--info",
        action="store_true",
        help="Print detailed information about merged datasets"
    )
    
    args = parser.parse_args()
    
    # Validate input paths
    for path in args.parquet_paths:
        if not os.path.exists(path):
            print(f"Error: Path {path} does not exist")
            return
    
    print(f"Merging datasets from: {args.parquet_paths}")
    print(f"Output directory: {args.output_dir}")
    print(f"Merge strategy: {args.merge_strategy}")
    
    # Merge datasets
    merged_datasets = merge_parquet_datasets(
        args.parquet_paths, 
        args.output_dir, 
        args.merge_strategy
    )
    
    if args.info:
        print_dataset_info(merged_datasets)
    
    print(f"\nMerge completed successfully! Check {args.output_dir} for output files.")


if __name__ == "__main__":
    main()